### ISSUE TITLE
workflow-core vs. Hangfire

### ISSUE THREAD

**Issue by ersenbasaransen** [danielgerlag/workflow-core#1141]
Hi @danielgerlag,

How workflow-core library differs from Hangfire? When to use workflow-core and when to use Hangfire?

**Comment by Viktor-36** [comment]
**Hangfire** is used to perform background processing. For example, you can create some recurring job that should run in the background and Hangfire will help you to schedule this background job to run every day at 5 A.M. or you can put there some jobs to queue and they will be processed by the worker later.

**Workflow Core** is different, because it is used for handling workflows. For example, you have three tasks those need to be processed in some order and order can be also dependent on the inputs or outputs (from other tasks). And you can also have some task that is waiting for some event (e.g. some action performed by the user). There are also transactions in Workflow Core and you can easily repeat all tasks in the transaction, if one of tasks fails. Workflow can also contain some data that can be stored in persistence storage (I think this.

I am not sure if I explained it properly, but both libraries should be used for other use cases.
