### ISSUE TITLE
Multi user/tenant persistence of same workflow type? 

### ISSUE THREAD

**Issue by MagnusJohansson** [danielgerlag/workflow-core#115]
I would like to manage several instances of the same workflow type.
I.e. Workflow-Core hosted behind an API to serve multiple users.
Each user would have his/her own instance of the workflow, identified by a user id.

The workflows has to be persisted for long running tasks, so if _n_ number of users have started a workflow, _n_ instances (of the same workflow type/definition) has to be persisted.

Is this possible?

What would be the best approach?

**Comment by germandb** [comment]
This is the default way for Workflow.Core to work. Every time you call startWorkflow a new instance of the workflow definition is created. 
You can look into the examples, https://github.com/danielgerlag/workflow-core/tree/master/src/samples

**Comment by danielgerlag** [comment]
@MagnusJohansson could you clarify what you are trying to achieve?
You can attach a custom data class to any workflow in order to house the `user id`, and there is no limit to the number of workflow instances per type that can be persisted.  If you are building a multi-tenant application, you may want to build a security layer around the workflow library to segregate each tenant's data.
