### ISSUE TITLE
Workflow steps history database

### ISSUE THREAD

**Issue by ccpony** [danielgerlag/workflow-core#12]
Would be nice if each workflow step is individually tracked and stored (i.e., date/time each step was completed with perhaps some user definable information also stored per completed step).  Ultimately, this information could be reflected in an user interface such as GoJS.

If this is worth pursuing, I could start on this with some guidance from you.

**Comment by danielgerlag** [comment]
This info is currently stored in the ExecutionPointer, of which each workflow instance has an array that is persisted to the chosen provider.  In MongoDB, it's quite easy to see, but currently, if you are using one of the relational DB providers, these are serialized as a json string to a varchar field.  I am in 2 minds about splitting them out into a separate table, perhaps you could help me decide ;)

**Comment by ccpony** [comment]
I think that the main benefit of creating a new Db table that stores Step instances is the ability to store user definable information per Step as it is triggered.

**Comment by danielgerlag** [comment]
So, I have added an ExtensionAttributes field on the ExecutionPointer class, and if you look at WorkflowCore.Users, you can see an example of a decoupled extension package making use of this.  I would like to split the execution pointers out into a separate table for the relational DB providers, but this will be a breaking change, no migration for existing databases.  Given that this project in only 2 months old, we should probably do this sooner rather than later.

**Comment by danielgerlag** [comment]
Actually, we could provide a migration for existing databases, I'm just not sure it is worth it given how new the project is.  Thoughts?
