### ISSUE TITLE
Wait for PublishEvent() to complete

### ISSUE THREAD

**Issue by andy-dumbell** [danielgerlag/workflow-core#126]
Hi there,

I'm in the early stages of exploring workflow-core. Really impressed so far!

My use case is predominantly based on user events. e.g. somebody reports an incident. The next step is to 'WaitFor' the user to click a button in an app (web, iOS etc) which in turn executes the PublishEvent() method to progress the workflow. This appears to run in a different thread so my main thread continues before the workflow update is complete. 

How do I wait for the workflow engine to complete its processing post PublishEvent()?

Ideally I would like my API to return a response to the app that reflects the change in workflow state so that the app can alter it behaviour appropriately.

Any guidance you can offer would be appreciated.

Thanks, Andy

**Comment by danielgerlag** [comment]
I think you would have to implement a custom Step within your workflow to signal some kind of locking mechanism.  You could also possibly inject `IDistributedLockProvider` that WorkflowCore uses internally, which would also work if you were running a cluster, then it wouldn't matter which node actually executed the workflow, you could still synchronize the locks.  That being said, the idea behind workflow though is to be a long running background process, I'm not 100% your use case fits to control a short lived user interaction?

**Comment by andy-dumbell** [comment]
Thanks for your feedback Daniel. I'll look into IDistributedLockProvider. BR, Andy

**Comment by eddie3716** [comment]
Hello.  I know this question is 3 months old, but I'm in a similar situation.  I have long-running workflows, but I need to wait for them to finish.  I already have a scheduler system in place that manages job priorities and strict ordering (because there are certain workflows that cannot run at the same time).  I have a tenant-based system where a single tenant can only have one workflow running at any given time.  The distributed lock system looks like a decent way to manage this, but I noticed another way, in one of your unit tests in test\WorkflowCore.Testing\WorkflowTest.cs, you have a method called WaitForWorkflowToComplete.  We already use a similar kind of "waiting" scheme in our existing test frameworks.  I'm going to experiement with a system similar to this in my job scheduler.  Do you have any thoughts on this, or words or caution?

**Comment by roycai1234** [comment]
I am in the same situation, I want to update the user interface after PublishEvent is fired (and the workflow is run into next step). I use Task.Delay, but it's unreliable, and user experience is not good.

await host.PublishUserAction(key,UserName, value);
await Task.Delay(3000);
var openUserActions = await host.GetOpenUserActionsAsync(workflowId);
