### ISSUE TITLE
mysql provider

### ISSUE THREAD

**Issue by zenglei286** [danielgerlag/workflow-core#143]
Hi,
do you have any plan to implement mysql provider for workflow core ??

**Comment by danielgerlag** [comment]
I don't have any plans for this, but it would be quite easy to do, since we already have a shared entity framework package that could be leveraged.  I would encourage you to look at how the SQL Server and PostgreSQL providers work and submit a PR for a MySQL provider... otherwise, if there is enough interest from the community I could try make some time to implement one.

**Comment by zenglei286** [comment]
thanks

**Comment by cnayan** [comment]
Yes, it's easy. We already did it. But it has not been published, so far.

**Comment by TarasKovalyk** [comment]
What about provider for CosmosDB?

**Comment by TarasKovalyk** [comment]
@danielgerlag 
Yes agree. But exception will be thrown during MongoClient initialization. Since this client cannot work with CosmosDB uri.

**Comment by danielgerlag** [comment]
I have no short term plans to create a cosmos db provider, but I encourage you to submit a PR... I can provide guidance on how to implement one.

**Comment by ibabuashok** [comment]
@danielgerlag 
We are looking to use it with SQL API of Cosmos DB. 
Can you please provide guidance on implementing a cosmos db provider?

**Comment by danielgerlag** [comment]
I would look at the MongoDB implementation... I think CosmosDb should be similar

**Comment by danielgerlag** [comment]
CosmosDB provider has been added
