### ISSUE TITLE
Feature Request: Wait for workflow to finish

### ISSUE THREAD

**Issue by Kahbazi** [danielgerlag/workflow-core#162]
I want to use workflow-core in a website and I need to be able to start a workflow in a http request and when it's over I send the data of workflow as response. 

Basically I need to be able to wait for a workflow to finish. I looked at the source code and I didn't find anything for this.

So I came up with a solution and I implement this feature but I'm not sure that I did everything right. Do you have intention to add this feature? if so I can submit a PR so we can discuss the solution.

**Comment by ronnyek** [comment]
I believe with the waitfor events, you could simulate this... but I am assuming you mean you want to trigger a workflow synchronously and block until its complete?

**Comment by Kahbazi** [comment]
Based on my requirement, I don't think it's peculiar.
I want to use workflow-core as service composition in a web application so I can register workflows at the runtime using `DefinitionLoader` and then have an endpoint for executing that workflow. Usually my workflows are not long-running. Also I don't want to change the workflows from async to sync, I need them to be async since I want to use parallel for my service composition.

So with this assumption do you mind if I submit a PR and you take a look at it, and if you decide that it's a good feature merge it to your library?

**Comment by danielgerlag** [comment]
Ok, were you thinking of having a way to execute a workflow outside the `WorkflowHost`?

**Comment by Kahbazi** [comment]
No, I want to use workflowhost. I just need a method in workflowhost which waits until a specific workflow is done. Something like this :

    var workflowId =  await host.StartWorkflow("test");
    await host.WaitForWorkflowToEnd(workflowId);

**Comment by danielgerlag** [comment]
Perhaps, we need some kind of internal notification publisher, that one could subscribe to, which would emit events like 'WorkflowComplete` or `WorkflowStarted`, etc...?

**Comment by Kahbazi** [comment]
I use PauseToken based on this article https://blogs.msdn.microsoft.com/pfxteam/2013/01/13/cooperatively-pausing-async-methods/
If you can review it, I submit a PR

**Comment by danielgerlag** [comment]
The interfaces would need to be pub/sub centric... Another option would be to build a `SyncWorkflowExecutor` that would hold a lock on the workflow and execute it from start to end with a timeout.

**Comment by Miggleness** [comment]
@danielgerlag A separate executor does sound like a good option.  I'm starting my integration project soon and may contribute to that feature.

**Comment by danielgerlag** [comment]
![image](https://user-images.githubusercontent.com/2357007/44373998-ef38cd80-a4a0-11e8-98a1-be44f5a95567.png)


I'm not sure the persistence provider needs to change for it... but you would want to hold a lock on the workflow instance for the duration with the implementation of `ILockProvider`

**Comment by johnbouma** [comment]
I've implemented this by putting a task completion source in my data class and creating a final step in the flow that sets that task completion source.  Then your create a new instance of your data class, get the reference to the task completion source 's task, start the pipeline pushing in the data object and await the task.

**Comment by kpko** [comment]
Hi,

I'm currently working on a project that would benefit from a workflow engine like WorkflowCore. Our users should have the possibility to design workflows using a graphical designer and watch the progress while executing them similar to Microsofts Flow user interface, either executing a long-running workflow over time or a shorter workflow that runs synchronously in a single HTTP call. 

If I read the [pull request of @Kahbazi](https://github.com/danielgerlag/workflow-core/pull/166) correctly, the implementation using an EventBus solves that: 
- It could be enhanced to output more events for things like StepStarted, StepError and StepCompleted that gives us the opportunity to subscribe to those events from our UI.
- It gives us a method to start the execution and wait for its completion that would enable us executing a shorter workflow in an HTTP or gRPC API method.

@danielgerlag You were looking for a more simple solution, wouldn't this implementation be simpler than implementing a separate synchronous workflow executor? Though, to be honest, maybe I'm too biased here because it would solve the "observability" problem too.

**Comment by kpko** [comment]
Hi everyone,

now that the lifecycle events have landed in master, we can use the provided events to help to execute a workflow synchronously.

Feel free to use my implementation here https://gist.github.com/kpko/f4c10ae7646d58038e0137278e6f49f9.

@danielgerlag: Does it make sense to include this functionality into WorkflowCore?

Thanks everyone!

**Comment by Kahbazi** [comment]
yeah that's exactly what I need :) although if it's going to be in WorkflowCore I prefer to have a `WaitAsync(string workflowInstanceId)` method so I could have the workflow instance id before I await for a workflow to finish.
I wanted to ask you a question, I'm planning to work on same project that you've mentioned, a user interface for workflow core which users can design and track workflows. Do you have any suggestion for which framework to use or perhaps have any plans to make it open source?

**Comment by kpko** [comment]
So you would like to start the workflow with the default StartWorkflow() method and then wait for the result via another method? That would be possible, although one could falsely assume that they can wait for any workflow instance. In reality it's limited to a workflow on the same workflow host at the moment. 

If that's okay and @danielgerlag approves of this, I would pull the functionality into WorkflowHost and initiate a pull request.

Regarding the user interface: The focus of the user interface we will be developing functions like an enterprise service bus designer. Consultants should be able to design "data flows" rather than typical workflows. This the user interface will be highly specialized in regards to data mapping, ETL processes and such. That's why I'm not sure it's a good candidate to open source it as a user interface to WorkflowCore per se. On the other hand, I can imagine open sourcing components of the application that are reusable, we have to see how contracts with our customers come into play.

Technology-wise we're using Angular (latest version) on the frontend and ASP.NET Core (+SignalR) on the backend. Also we will most likely use the [Monaco editor](https://microsoft.github.io/monaco-editor/index.html) for script tasks.

**Comment by Kahbazi** [comment]
> So you would like to start the workflow with the default StartWorkflow() method and then wait for the result via another method? That would be possible, although one could falsely assume that they can wait for any workflow instance. In reality it's limited to a workflow on the same workflow host at the moment.

Yes, and you are right, until there's a multi node support for events it only works for workflows on the same node, but again we have somehow the same problem with when `DefinitionLoader` register a workflow it will only registers on the same node, so maybe it's ok for now.

I suggest we add `WaitAsync(string workflowInstanceId)` and `StartAndWaitAsync(...)`. Even `WaitForAllAsync()` might come in handy. 

@danielgerlag what do you think?
> The focus of the user interface we will be developing functions like an enterprise service bus designer
That's exactly what I'm developing right now. Are you using any libraries for designing the workflows? Are you using the `DefinitionLoader` for registering workflows?

**Comment by davidimhoff** [comment]
https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/SyncWorkflowRunner.cs
