### ISSUE TITLE
Is workflow-core a "state machine"?

### ISSUE THREAD

**Issue by meatballcoder** [danielgerlag/workflow-core#177]
I was hoping someone could tell me the difference.  What is the difference between workflow-core and stateless?  Are you both doing the same thing?

**Comment by peterkozak** [comment]
I personally use it in combination. workflow-core drives the workflow and each workflow step is a stateless statemachine running as a ServiceFabric Actor.

**Comment by danielgerlag** [comment]
I think of a state machine as something that manages the state of something without and end to the process, so it could be in a specific state indefinitely.  A workflow is a process that has an end, so you might trigger a workflow when something transitions into a new state, that state remains even after the workflow completes.

**Comment by eddie3716** [comment]
I've used both workflow-core and stateless to build workflow systems with definite beginnings and definite endings.  I even tried to build in a rudimentary persistence mechanism into stateless (so that I could resume workflows over a service restart, server reboot, etc), but part way through i realized my implementation was awful and not appropriate.  Stateless is great if you can live within the narrow parameters that stateless is great out.  As soon as you start needing something more robust, like state persistence, you're better off looking for a robust workflow solution built with those features in mind.

**Comment by nanhishweta-26** [comment]
Any update on state machine workflow?
