### ISSUE TITLE
Extend the OnError method to support custom retry strategies to handle the cloud transient errors

### ISSUE THREAD

**Issue by KannaKaranam** [danielgerlag/workflow-core#20]
https://msdn.microsoft.com/en-us/library/microsoft.practices.transientfaulthandling.aspx

**Comment by thebrianmoore** [comment]
You can either use a .While clause or a .Recur clause, but Is there a cleaner, prettier way to implement a retry strategy instead of doing it manually? Am I missing something in the documentation and/or the Intellisense for the .OnError clause? It appears to only have the option to retry and to set a retry interval, but not a number of times to retry.

**Comment by VictorioBerra** [comment]
@thebrianmoore Came here searching for the exact same information. How many times is it going to retry?
