### ISSUE TITLE
Is it possible to load dynamic steps to a running Workflow?

### ISSUE THREAD

**Issue by MouradAissani** [danielgerlag/workflow-core#213]
For exemple : i have 2 workflows (WF1,WF2) ,

- WF2 is loaded by reflection (dll) while WF1 is running.
- I want to inject the loaded steps from WF2 in the WF1 to be executed, how can i achieve that (if possible)?
-My goal here is to not persiste 2 WFs on the DB, but only 1 WF with the steps union (WF1+WF2)

Thank you

**Comment by germandb** [comment]
You can't inject the steps at running time because the definition of the steps its loaded when you register the Workflow.

But I think that you could create a Step that register and start a second Workflow, what you need to do is pass the Workflow definition and the Dll in the constructor of the step and use a waitfor step so you could wait until your second Workflow sends an event that its complete.
