### ISSUE TITLE
Question: Why is GetWorkflowInstances obsolete?

### ISSUE THREAD

**Issue by incompletude** [danielgerlag/workflow-core#252]
Hey guys, sorry if this is a dumb question, I can't find any alternatives to this method inside the IPersistenceProvider interface. Is there a reason for this? Getting instances for a specific workflow sounds very useful to me.

I need to build a RESTful endpoint that shows every instance and its details (workflow it belongs, datetimes, tasks statuses, etc). I also need to be able to manually suspend or terminate a given instance. Is it possible to achieve this with workflow-core?

**Comment by danielgerlag** [comment]
It's deprecated in favor of the search index

https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.Providers.Elasticsearch

**Comment by danielgerlag** [comment]
@incompletude does this make sense?

**Comment by incompletude** [comment]
Ofc. Perfect, thx.

**Comment by mvanhelmont** [comment]
@danielgerlag for me this does not make complete sense! This because for a simple dashboard with running and terminated workflows you always need to add a extra depenency on a search provider. It makes the setup for a simple workflow scenario more complexer.

for searching the data would this make sense and a better solution.

**Comment by danielgerlag** [comment]
Great observation!  I have no problem with building extensions around the existing persistence providers to enable these use cases... however, I'd like to keep them outside of the `IPersistenceProvider` interface because
 * It should only implement what is needed by the core library
 * Returning an `IQueryable` can introduce problems see http://www.codetunnel.io/should-you-return-iqueryablet-from-your-repositories/
 * Not every datastore lends itself to returning an un-executed query, eg. Redis, DynamoDB, etc....
