### ISSUE TITLE
Query - Suspending workflow from the step

### ISSUE THREAD

**Issue by Shubbi** [danielgerlag/workflow-core#275]
Hi,
I am suspending the workflow from the step by having code like the following :

public override ExecutionResult Run(IStepExecutionContext context)
{
      context.Workflow.Status = WorkflowStatus.Suspended;
      return ExecutionResult.Next();
}

Is there any issue with this?

The reason I'm doing this is because we will have workflow templates (not just instances) created on the fly from the web interface.
Is there a way to to tell a step to suspend workflow in the Json template directly? 

Also - Is it possible to change the NextStepId at run time from the step itself ?

Regards

**Comment by danielgerlag** [comment]
That might work but it won't be guaranteed to always work... it also won't publish any of the notification events regarding suspension... you do bring up a valid point though... I will investigate how to better support this.

Setting the `NextStepId` from within a step would introduce tight coupling between the workflow definition and it's steps, I would not recommend it.
You can use the `ExecutionResult.Outcome` method to select different paths through the workflow... but you can't explicitly set the NextStepId... or you can set pass some data back to the workflow so that it can make the decision where to go.

**Comment by Shubbi** [comment]
Suggestion (Might be bad :( )
- Can we have workflowhost/workflowcontroller available in the IStepExecutionContext parameter ....so that we can directly call suspend/terminate methods .......
These are created as singleton from the service .....so are anyway going to have a single instances

- Another thing could be having extension methods like this:

        public static ExecutionResult SuspendWorkflow(this IStepExecutionContext context)
        {
            context.Workflow.Status = WorkflowStatus.Suspended;
            return ExecutionResult.Next();
        }

        public static ExecutionResult TerminateWorkflow(this IStepExecutionContext context)
        {
            context.Workflow.Status = WorkflowStatus.Terminated;
            return ExecutionResult.Next();
        }

        public static ExecutionResult CompleteWorkflow(this IStepExecutionContext context)
        {
            context.Workflow.Status = WorkflowStatus.Complete;
            return ExecutionResult.Next();
        }

- This extension might allow you strongly type Data object 
public static WorkflowContextData GetWorkflowContextData(this IStepExecutionContext context)
        {
            return ((WorkflowContextData) context.Workflow.Data);
        }

**Comment by crashsol** [comment]
@Shubbi  this is wonderful。 i also want to direct terminate the workflow in step, rather than use
 `
.If(data => data.Data.Value!=xx).Do(sequence =>
 sequence.StartWith<DoSomething>()
.EndWorkflow()
)
`
