### ISSUE TITLE
Event trigger wait for multiple times?

### ISSUE THREAD

**Issue by Curarpika** [danielgerlag/workflow-core#297]
I'm using re-enter step method to jump to previous wait for step which I already publish a event to triggered once, and the old event triggered re-entered wait dor again. how to make a event which has been processed not been processed again.  Please help thx

**Comment by danielgerlag** [comment]
You can use an effective date on `WaitFor` and `PublishEvent`... you should see this parameter in the method overloads.

**Comment by Curarpika** [comment]
I think this is about how to handle events which have been processed when re-entering previous steps,
I found this code in WorkflowConsumer.SubscribeEvent()
```
await persistenceStore.CreateEventSubscription(subscription);
            var events = await persistenceStore.GetEvents(subscription.EventName, subscription.EventKey, subscription.SubscribeAsOf);
            foreach (var evt in events)
            {
                await persistenceStore.MarkEventUnprocessed(evt);
                await QueueProvider.QueueWork(evt, QueueType.Event);
            }
```

when it's re-stepping in the a wait for step, the GetEvents will return the processed events and have been set to unprocessed which cause a infinite loop. I sample filtered the processed ones, for now it works fine.

Just wondering why need to set event unprocessed, many thanks, sir.

**Comment by danielgerlag** [comment]
So that events can be published before they are actually subscribed to... it's all about the effective date/time

**Comment by wangshuai-007** [comment]
Now I have the same error of  `WaitFor`.
And my problem is come from `UserTask`.
According to the [Human(User) Workflow](https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample08),I create a `HRApproveFlow`,the flow is like this:
```c#
public void Build(IWorkflowBuilder<HolidayInfo> builder)
{
    builder
        .StartWith(c =>
        {
            if (c.Workflow.Data is HolidayInfo data)
            {
                Console.WriteLine("---------------------------------------");
                Console.WriteLine(
                    $"收到来自用户：{data.UserId}的请假申请，时间：{data.StartDay},请假天数：{data.Days},理由：{data.Reason}");
            }

            return ExecutionResult.Next();
        })
        .If(data => data.Days > 5).Do(autoThen =>
            autoThen.StartWith(s => ExecutionResult.Next())
                .Output(step => step.HolidayState, data => HolidayState.Refuse)
                .Output(step => step.ApproveDesc, data => "不能请高于5天的假！"))
        .Then<PushEventData>()
        .UserTask("是否同意以下的请假申请？", data => $"domain\\{data.UserId}")
        .WithOption("yes", "同意").Do(then => then
            .StartWith(context =>
            {
                Console.WriteLine("HR approved");
            })
            .Then<SendMessage>()
            .Input(step => step.HolidayInfo, data => data)
            .Input(step => step.HolidayInfo.HolidayState, data => HolidayState.Accept)
            .Input(step => step.HolidayInfo.ApproveDesc, data => "HR同意")
            .Output(step=>step.ApproveDesc,data=>data.HolidayInfo.ApproveDesc)
        )
        .WithOption("no", "拒绝").Do(then => then
            .StartWith(context => Console.WriteLine("HR refuse"))
            .Then<SendMessage>()
            .Input(step => step.HolidayInfo, data => data)
            .Input(step => step.HolidayInfo.HolidayState, data => HolidayState.Refuse)
            .Input(step => step.HolidayInfo.ApproveDesc, data => "HR拒绝," + data.ApproveDesc)
            .Output(step=>step.ApproveDesc,data=>data.HolidayInfo.ApproveDesc)
        )
        .Then<HelloWorld>()
       .Then(context => Console.WriteLine("end"));
}
```
the `HRApproveFlow` is running in Service,And I create another host(as HR User) to listen `UserAction`  by `GetOpenUserActions`.
After HR choose `yes` or `no`,the `UserTask` will run continue,But the `HelloWorld` step will run multiple times.
I know `UserTask`  used [WaitForEvent](https://github.com/danielgerlag/workflow-core/blob/32fedfd528e9d8f8eeae7a3b9500d84c5c411c39/src/extensions/WorkflowCore.Users/Primitives/UserTask.cs#L42),
So, I think this may be caused by [_queueProvider.QueueWork](https://github.com/danielgerlag/workflow-core/blob/32fedfd528e9d8f8eeae7a3b9500d84c5c411c39/src/WorkflowCore/Services/WorkflowController.cs#L87); while waiting for HR Client `PublishUserAction`, the queue is loaded with multiple `Steps`. After the server receives the `UserAction`, they are executed from the background at the same time, which leads to the problem of repeated execution.
I tried lock(`if (_host.LockProvider.AcquireLock(context.ExecutionPointer.Id, new CancellationToken()).Result)`) and `context.PersistenceData`, but they are not guaranteed to be executed only once;
So, **what is the correct way to make Step execute only once?**

**Comment by wangshuai-007** [comment]
I know why my `Step` execute multiple times.
When I build this step,I test much times,and some of  the flow is not complete(caused errors), the host will retry `ExecutionPointer` in `Subscription`
Every time a new `UserAction` sented,all the `WaitFor` step will execute, So the step will run multiple times.
If you use `UseSqlServer`,Just exec this SQL:
```SQL
DELETE wfc.Workflow WHERE  CompleteTime IS NULL
```
