### ISSUE TITLE
Using BlockingCollection instead of busy loop in RunWorkFlows()

### ISSUE THREAD

**Issue by qazq** [danielgerlag/workflow-core#32]
I have a question about RunWorkflows() in WorkflowThread. 

In the worse case, a new workflow will be started after 500 milliseconds. Is it possible to use BlockingCollection(or other similar methods) to blocking each thread until getting a new workflow ID?

**Comment by danielgerlag** [comment]
That would depend on the implementation of the QueueProvider... you could for example do that with the in memory queue provider for single node instances... but external queue providers may not support that.
Also, you need a way to gracefully shutdown the thread pool.  
Is there a specific issue you are running into because of how it is currently implemented?

**Comment by qazq** [comment]
Hi @danielgerlag , thanks for your swift reply. There is no specific issue I am running into. I would like to let my task start immediately when I adding a new one. I can implement it in memory query. Thanks a lot.
