### ISSUE TITLE
What happens in case of failure ?

### ISSUE THREAD

**Issue by ssougnez** [danielgerlag/workflow-core#336]
Hi,

I'm building a big application around workflow core and I'm about to test it on a multi cluster environment. I'm planing on using Redis as a DLM and RabbitMQ as the QP.

While I have no doubt it will work, I'm wondering how you handled a failure in one of these two components ? Say that everything works well, then, for any reason, Redis goes down, what will happen with all the workflows handled by workflow core ? Will everything stop (which I hope), or do we get some unexpected behavior such as workflows handled by all the machine of the cluster => multiple execution and so on ?

**Comment by danielgerlag** [comment]
If the DLM is down... no workflows will be able to process because it won't be able to acquire a lock.
If the queue is down, also no workflow will execute because the worker pool won't be able to pull any work.
You can also now use Redis as the queue provider as well, so no need to have RabbitMQ in the mix.

**Comment by ssougnez** [comment]
Ha ha ha,

This library is simply magical... It always does what I expect it to do. You definitely deserve a blog post on my blog that no one read ! I'll write it soon and post it here ;-)
