### ISSUE TITLE
Add Ability to De-Register Definition

### ISSUE THREAD

**Issue by DucAnhPhi** [danielgerlag/workflow-core#370]
To my knowledge, there is no way to de-register a workflow definition.
Would it be possible to add this feature?

**Comment by danielgerlag** [comment]
Yes, you'd simply need to remove it internally from the `WorkflowRegistry`

**Comment by leobel** [comment]
Hi @danielgerlag does the library exposes any method to remove the definition? I'm looking to the source code and I don't see any method for that. I think `IWorkflowRegistry` could have an `UnRegisterWorkflow(string id)` and `UnRegisterWorkflow(string id, int version)` method for that. 

Also I'd like to know when exactly is a good time to un-register a workflow definition. I was thinking to do it during the execution of a specific step that I know is always be the final step on each workflow, but it doesn't seems the right place, because it will break something internally (in the remaining executions after the last step gets executed). Maybe the core could provide a callback to handle when the workflow have already finished?

**Comment by danielgerlag** [comment]
What's the use case this is trying to solve?

**Comment by leobel** [comment]
I want to remove the workflow definition from the registry after the workflow has finished

**Comment by leobel** [comment]
> What's the use case this is trying to solve?

It seems to me that eventually you can end with a lot of memory been in use because you don't clean it after a workflow finish

**Comment by danielgerlag** [comment]
Only 1 instance of a workflow definition exists per type... it is not duplicated for every workflow instance,

**Comment by leobel** [comment]
> Only 1 instance of a workflow definition exists per type... it is not duplicated for every workflow instance,

Ok, but you can have multiple versions (each one on memory as well) and what if you have hundreds or thousands of workflow definitions? Don't you think it could be recommendable to avoid keep all this instances on memory? After you run each of this workflow definitions at least once you will end with it on memory forever right?

**Comment by bbollard** [comment]
Bumping this -- I just want to confirm @leobel's statement:

> you can have multiple versions (each one on memory as well) and what if you have hundreds or thousands of workflow definitions

Meaning you can have long running workflows, some at version 1, others at version 2, 3, etc. so that as you update the workflow definition, you not break running instances at the older version.
