### ISSUE TITLE
Compatibility with IHostedService

### ISSUE THREAD

**Issue by AMalininHere** [danielgerlag/workflow-core#380]
Currently `IWorkflowHost` has an API similar to `IHostedService` in case of starting and stopping of service. I think it would be great if `IWorkflowHost` would inherit `IHostedService`.

**Comment by danielgerlag** [comment]
Sounds like a good idea :+1

**Comment by terry-delph** [comment]
Hi @AMalininHere,
I can see your PR #387 has been merged.
I have a question when adding WorkflowHost as a Hosted Service.

```
//Microsoft
IServiceCollection.AddHostedService<WorkflowHost>()
```
registers WorkflowHost as 
`IServiceCollection.AddTransient<IHostedService, THostedService>();`

and

```
//Workflow-Core
IServiceCollection.AddWorkflow()
```
registers WorkflowHost as
`IServiceCollection.AddSingleton<IWorkflowHost, WorkflowHost>();`

When I access an injected IWorkflowHost in a Controller it is not the one that has started, which is assumed to be the singleton.

Instead of using Microsofts' extension AddHostedService, should I be adding it to the ServiceCollection as follows?

```
IServiceCollection.AddTransient<IHostedService, IWorkflowHost>(
     serviceProvider => serviceProvider.GetService<IWorkflowHost>()
);                
```
If I do this, I get the instance that is running from the IHostedService registration.
