### ISSUE TITLE
Console.ReadLine() is not working inside Step class 

### ISSUE THREAD

**Issue by 13atec030** [danielgerlag/workflow-core#385]
In my workflow, I need to take user input using Console.ReadLine(), but My App exiting on Console.ReadLine() within StepBody class's method: ExecutionResult Run(IStepExecutionContext context)

Find below my source code:
public class WorkflowStart : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            **var result = Console.ReadLine();  // This line is not executing** 
            Console.WriteLine("WorkflowStart step.");
            return ExecutionResult.Next();
        }
    }

Any, help is appreciated.

Thanks,

**Comment by danielgerlag** [comment]
That will not work because the workflow is executed as a background task.  You have to create a workflow that waits for an external event. Then run the readline in your code and pass it to the workflow by publishing an event.

See tutorial page here:
https://workflow-core.readthedocs.io/en/latest/external-events/

See sample 4 here:
https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample04

**Comment by 13atec030** [comment]
Thanks Danielgerlag, it worked for me.
