### ISSUE TITLE
It will support input from user ?

### ISSUE THREAD

**Issue by rizwika94** [danielgerlag/workflow-core#386]
Hi 

 We are using workflow for past few days, we are facing issue with getting input from the user in 
 public override ExecutionResult Run(IStepExecutionContext context)
  {
           // here we need to fetch the input
   }

**Comment by danielgerlag** [comment]
That will not work because the workflow is executed as a background task. You have to create a workflow that waits for an external event. Then run the readline in your code and pass it to the workflow by publishing an event.

See tutorial page here:
https://workflow-core.readthedocs.io/en/latest/external-events/

See sample 4 here:
https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample04
