### ISSUE TITLE
JSON Based ForEach -- Example Needed

### ISSUE THREAD

**Issue by venugopalsjce** [danielgerlag/workflow-core#393]
Hello,
I am working on creating a workflow where in I need to iterate few steps over a collection.
I somehow, am not able to get it. Kindly help me out with an example.
Attached is my workflow JSON. In the JSON, I have specified "MyCollection" which is a collection of integers --> `List<int>() { 1,2,3,4}`

[ForEachExample.txt](https://github.com/danielgerlag/workflow-core/files/3583860/ForEachExample.txt)

Attached also, is the output, where I am getting an exception "Object must implement IConvertible" while executing the "ForEach" step.
![image](https://user-images.githubusercontent.com/4627513/64427474-f2642300-d0ce-11e9-85b5-a0f768cf441c.png)

Thank you,
Venu

**Comment by danielgerlag** [comment]
I don't see any problems with this.. can you confirm the data type of "MyCollection" is what you expect?

**Comment by venugopalsjce** [comment]
Yes, "MyCollection" is a list of integers. What could be the problem?

**Comment by danielgerlag** [comment]
I don't see any issue with that, the problem might be something else, not related to the collection or foreach?

**Comment by venugopalsjce** [comment]
Can you please provide a working example for ForEach based on JSON ?
I'm kind of stuck here. The example would be of great help. Thanks.

**Comment by venugopalsjce** [comment]
Hello,
Could you please provide an update on this?

Thank you.

**Comment by danielgerlag** [comment]
I won't be adding a specific example for this, I think the tutorial is enough... however, if you send me a sample project that reproduces this issue, I can try debug it for you.

**Comment by wolgasster** [comment]
I'm getting the same error while deserializing a collection from the data class' property for the "Inputs" parameter of `WorkflowCore.Primitives.ForEach` step type. The issue is that during Inputs deserialization `DefinitionLoader.BuildScalarInputAction` is called and it uses `System.Convert.ChangeType(object value, Type conversionType)` method which requires a convertible object implements `IConvertible` type, but collections do not.

By the way, I don't see any DefinitionLoader's unit test in the WorkflowCore solution which cover exactly this scenario. It is used `stored-definition.json` asset but it contains not all possible step types.

See a project with an example in attachment [ForEachDefinitionLoader.zip](https://github.com/danielgerlag/workflow-core/files/4070472/ForEachDefinitionLoader.zip).
