### ISSUE TITLE
Migrate from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by kinosang** [danielgerlag/workflow-core#582]

**Comment by danielgerlag** [comment]
What's the motivation?

**Comment by Suriman** [comment]
Possibly performance

**Comment by kinosang** [comment]
System.Text.Json is faster and smaller than Newtonsoft.Json. And Asp.Net Core itself now depends on System.Text.Json, migrate to System.Text.Json can reduce size of compiling outputs and the complexity.

**Comment by phillip-haydon** [comment]
Also need to remove the type information from the serialization. It's not needed and only causes problems with events.

**Comment by danielgerlag** [comment]
> Also need to remove the type information from the serialization. It's not needed and only causes problems with events.

The type information is essential.
What problems does it cause?

**Comment by phillip-haydon** [comment]
>  What problems does it cause?

For event's it's not essential, it's just essential because of where the deserialization is done. If the deserialization of the event information is done prior to the execution of the step you can avoid the type information as you can rely on the type from the step.

It means I can't publish an event outside of the system in another language, or have an API that accepts an event without type information. For example if I published an event to a single API with the `Name` `Key` and `Body` I then need to look up this information to figure out what the type is in order to deserialize it then re-serialize it when I call `host.PublishEvent`.

The event body should be just data and nothing else so it shouldn't be constrained to a specific type.

**Comment by danielgerlag** [comment]
> For event's it's not essential, it's just essential because of where the deserialization is done. If the deserialization of the event information is done prior to the execution of the step you can avoid the type information as you can rely on the type from the step.

Not entirely accurate.,, it depends on your use case.  You could have properties or arrays of abstract types.

> It means I can't publish an event outside of the system in another language, or have an API that accepts an event without type information.

You can already do that.  You can write an API around the `host.PublishEvent` method and map the types however you want.  It sounds like you're suggesting that other processes written in other tech stack would access the DB directly, which I would not recommend.  The way the event is serialized is an internal concern of workflow core, should not leak out to the consumers.

**Comment by phillip-haydon** [comment]
>  You could have properties or arrays of abstract types.

For event's they should be poco's. Not an array of multiple different types. Trying to be too flexible like that only causes the problem that now exists.

> You can already do that. You can write an API around the host.PublishEvent method and map the types however you want. It sounds like you're suggesting that other processes written in other tech stack would access the DB directly, which I would not recommend. The way the event is serialized is an internal concern of workflow core, should not leak out to the consumers.

It's not even about touching the DB directly. If you expose an API where you take in the Event Name, Key, and Data, you need to deserialize that to the _actual type_, then pass that type to the `host.PublishEvent` so that the internal serialization has type info. 

So instead of a nice clean API where an event comes in and it's published to WorkflowCore, I have to write a bunch of type mapping. 

It also means that Workflow Core can't have a slim event publish library that can be used in other applications or even languages that can be used for publishing events. It's all tightly coupled together. i.e have an AWS Lambda written with Node which accepts a response from an external api that publishes the event to resume the WaitFor.

Instead I have to either have a separate event table which is then picked up and forwards it to WFC. Or have an api which publishes to WFC.

**Comment by danielgerlag** [comment]
> For event's they should be poco's. Not an array of multiple different types. Trying to be too flexible like that only causes the problem that now exists.

Yes, still POCOs... I didn't say anything about adding behavior to them.

> So instead of a nice clean API where an event comes in and it's published to WorkflowCore, I have to write a bunch of type mapping.

I would not recommend taking a raw object coming in from an array and passing it in as an event, that's almost the same as exposing your internal DB structure via an API.  They need to be able to evolve independently... so yes, having a mapping layer would enable that.

**Comment by danielgerlag** [comment]
Migrating away from Newtonsoft.Json is not something I would consider in the short term.  Removing type info from the internal serialization is not something I would support, but this library is MIT, so you are free to fork it and create your own. :)

**Comment by phillip-haydon** [comment]
:( I would rather just contribute to your project to help make it better. The only painpoints in WFC is logging and event publishing. Everything else is great. 

I did try ping you on twitter because I wrote a lock provider for PostgreSQL and unsure if it's something you would want/accept, or let me publish on nuget under the WFC naming.

**Comment by danielgerlag** [comment]
Can we solve your problem without removing the type info from the internal persistence concern?

**Comment by phillip-haydon** [comment]
I'm unsure, I started writing up a test project last night with the idea I would publish the event as a string and convert it on the WF Definition like.

`.WaitForEventOf<MyEvent>(...` which would handle the non-typed json deserialization. That was I can just forward the payload from the api directly to `host.PublishEvent` 

Unsure if that makes sense.

**Comment by phillip-haydon** [comment]
@danielgerlag the simpliest I can get it down to without changing WFC internals is:

I persist the following to a PostgreSQL queue. 

```
{
	"eventKey": "Sample.Delivery.Response.2055",
	"eventName": "SampleDeliveryNotification",
	"eventBody": {
		"responseCode": "00",
		"acceptedAt": "2020-06-24 07:01:33.542"
	}
}
```

Then I read that back out and forward it to Workflow Core

```
// Read a from separate event source
while (await results.ReadAsync(stoppingToken))
{
	var eventName = (string) results["name"];
	var eventKey = (string) results["key"];

	var body = JsonConvert.DeserializeObject(results["body"].ToString() ?? "{}") ?? new object();

	// Publish to Workflow Core	
	await host.PublishEvent(eventName, eventKey, body);
}
```

The workflow definition then casts it to JObject and then converts that to the type I want.

```
.WaitFor("SampleDeliveryNotification", x => $"Sample.Delivery.Response.{x.DeliveryId}")
    .Output(capture => capture.Response, step => ((JObject)step.EventData).ToObject<SampleDeliveryNotification>())
```

So `SampleDeliveryNotification` is in a shared library (in C#), or a known contract (in other languages like TypeScript), can be persisted without type information (no dependency needed on Newtonsoft and such)

Then the event body is deserialized to an object and passed to Workflow Core, when WFC persists it, as it's an `object` it's persisted without type info. 

![image](https://user-images.githubusercontent.com/895629/85546279-513f5c80-b64f-11ea-8783-3cfd63d417f6.png)

When WFC deserializes it, it becomes a `JObject`, which I then change to the type the Workflow Step expects.


I'm unsure how, but it would be nice if the `.Output` could specify a type _only_ when coming off a `WaitFor`. Since the rest of the workflow definition works 100% without issue. So if `WaitFor` could accept `Output<T>` where it could do something like, `if (EventData is JObject)` then it calls `ToObject<T>` otherwise it just casts `EventData` to `T`.

Or something like that.
