### ISSUE TITLE
SQL Server Persitance Provider not working with net5.0

### ISSUE THREAD

**Issue by digitalsigi** [danielgerlag/workflow-core#694]
I had to migrate to net5.0 I found, that PropertyBuilder no longer contains a definition for UseSqlServerIdentityColumn. See also [MS Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.sqlserverpropertybuilderextensions.usesqlserveridentitycolumn?view=efcore-3.1&viewFallbackFrom=efcore-5.0)

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'PropertyBuilder<long>' does not contain a definition for 'UseSqlServerIdentityColumn' and no accessible extension method 'UseSqlServerIdentityColumn' accepting a first argument of type 'PropertyBuilder<long>' could be found (are you missing a using directive or an assembly reference?)	WorkflowCore.Persistence.SqlServer	C:\GitHub\Workflow\workflow-core\src\providers\WorkflowCore.Persistence.SqlServer\SqlServerContext.cs	34	Active

**Comment by danielgerlag** [comment]
That's not a .net5 issue, that's an EF Core 5 issue. You can still use EF Core 3 with .net5.

**Comment by olegkap** [comment]
I think the problem, like in my case, when I use .net5 and EF Core 5 in my application and then I add WorkflowCore.Persistence.SqlServer that has dependency on EF Core 3 but since I already have EF Core 5, it choose that and then error occurs.
Perhaps the solution might b e to create new WorkflowCore.Persistence.SqlServer assembly that would be specific for EF Core 5.
Maybe something like WorkflowCore.Persistence.SqlServer.EF5 ?

**Comment by fusyd** [comment]
kinda same with #413

**Comment by fusyd** [comment]
@danielgerlag it looks kinda same with #413 
[UseSqlServerIdentityColumn was deprecated and replaced by UseIdentityColumn from efcore 3.X](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#provider-specific-metadata-api-changes), while SqlServer Persistence Provider depends on efcore 3.1.2. I see no problem using UseIdentityColumn() instead of UseSqlServerIdentityColumn() in [SqlServerContext](https://github.com/danielgerlag/workflow-core/blob/499abf928d45f02525cfe5fb444e2fd982183fae/src/providers/WorkflowCore.Persistence.SqlServer/SqlServerContext.cs#L31)?
