### ISSUE TITLE
why is the source code for workfllow netstandard2.0. that standard is obsolete and .net 5 is the now standard

### ISSUE THREAD

**Issue by stevensrf11** [danielgerlag/workflow-core#728]
Why is the source code for workfllow netstandard 2.0 when .net 5 is now the stanadard?
netstandard2.0 is obsolete at least the source code should be netstandard 3.0
I guess that shown this source code is obsolete and worthless

**Comment by ssougnez** [comment]
What a stupid statement. The code targets .net standard 2.0 in order to be usable in a large amount of application... You should test the library and check the release before telling stuff like this.

Wfcore is an awesome library up to date.

**Comment by danielgerlag** [comment]
@stevensrf11 as a library, we target the lowest `.net standard` version in order to maximize the number of applications that could use it... those applications can use any implementation such as `.net 5` or `.net core 3` or `.net framework 4.6`, etc... which implements the API surface defined by `netstandard 2.0`.  There is no `netstandard 3.0`

Please see the Microsoft docs for more info and guidance on when to target which version - https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by stevensrf11** [comment]
The why is the source code using .Net Standard 2.0?

 
 

Sent: Tuesday, December 15, 2020 at 7:17 PM

**Comment by stevensrf11** [comment]
What a stupid person to say this is a stupid statement

 
 

Sent: Tuesday, December 15, 2020 at 2:41 PM

**Comment by sandord** [comment]
Guys, please be kind to each other and refrain from making toxic remarks. Most of us are dependent on open source projects like this and the people spending their free time to work and contribute on open source projects deserve a respectful environment.

**Comment by stevensrf11** [comment]
ROFL I was being kind

 
 

Sent: Wednesday, December 16, 2020 at 5:27 AM
